# Generated by Django 3.2.25 on 2025-12-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20251219_1220'),
        ('classes', '0002_class_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', to='user.Customer'),
        ),
    ]
