# Generated by Django 3.2.25 on 2026-01-14 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_class_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='professional',
        ),
        migrations.AddField(
            model_name='class',
            name='professional',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'professional'}, null=True, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
