# Generated by Django 3.2.25 on 2025-12-23 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('duration', models.PositiveIntegerField(choices=[(15, '15 min'), (30, '30 min'), (45, '45 min'), (60, '60 min'), (90, '90 min')])),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('show_online', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='categories.category')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='services_collaborated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
