# Generated by Django 3.2.25 on 2025-12-23 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='collaborators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'professional'}, related_name='services_collaborated', to=settings.AUTH_USER_MODEL),
        ),
    ]
