# Generated by Django 3.2.25 on 2025-12-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=25, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('multibanco', 'MultiBanco'), ('mbway', 'MB WAY'), ('creditcard', 'Credit Card')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('mb_key', models.CharField(blank=True, help_text='MB Key used (e.g., CWR-828507)', max_length=50, null=True)),
                ('mb_entity', models.CharField(blank=True, help_text='MultiBanco Entity', max_length=10, null=True)),
                ('mb_reference', models.CharField(blank=True, help_text='MultiBanco Reference', max_length=20, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Payment expiry date', null=True)),
                ('mbway_phone', models.CharField(blank=True, help_text='Phone number for MB WAY (format: 351#912345678)', max_length=20, null=True)),
                ('ccard_payment_url', models.TextField(blank=True, help_text='IfThenPay payment page URL', null=True)),
                ('ccard_signature_key', models.CharField(blank=True, help_text='Signature key (sk) for verification', max_length=100, null=True)),
                ('request_id', models.CharField(blank=True, help_text='IfThenPay RequestId', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packs/')),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hours', models.PositiveIntegerField(default=0, help_text='Total hours included in this pack')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_added', models.PositiveIntegerField(help_text='Hours added from this subscription')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, help_text='Associated order for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_records', to='subscriptions.order')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.pack')),
            ],
            options={
                'verbose_name_plural': 'Subscription Histories',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
