# Generated by Django 3.2.25 on 2025-12-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20251218_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.customer',),
        ),
    ]
