# Generated by Django 3.2.25 on 2026-01-08 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20251219_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='professional',
        ),
        migrations.AddField(
            model_name='customer',
            name='professionals',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'professional'}, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
