# Generated by Django 3.2.25 on 2026-02-10 11:34

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_clients'),
        ('bookings', '0004_alter_booking_customer'),
        ('user', '0005_auto_20260202_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='professionals',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='user',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='professionals',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'professional'}, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('professional', 'Professional'), ('collaborator', 'Collaborator'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
