# Generated by Django 3.2.25 on 2025-12-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.CharField(blank=True, max_length=255, null=True)),
                ('room_equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('treatment_record_marking', models.BooleanField(default=False)),
                ('treatment_record_customer_file', models.FileField(blank=True, null=True, upload_to='treatment_customer_files/')),
                ('state', models.CharField(choices=[('confirmed', 'CONFIRMED'), ('it_arrived', 'IT ARRIVED'), ('paid', 'PAID'), ('missing', 'MISSING'), ('cancel', 'CANCEL')], default='confirmed', max_length=20)),
            ],
        ),
    ]
