# Generated by Django 3.2.25 on 2025-12-18 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bookings', to='user.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='professional',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='professional_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
